name = "profileimagefitservice"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-09"

[[r2_buckets]]
binding = "FRAMES_BUCKET"
bucket_name = "profile-frames"
preview_bucket_name = "profile-frames-preview"
