-- このmigrationはbaselineファイルで、本番では直接実行されません。
-- 本番DBへは `prisma migrate resolve --applied 0_init` コマンドでのみ
-- 「適用済み」として登録されます。このファイルは、スキーマの現状を
-- ゼロから作った場合のSQL定義として記録するための履歴ドキュメントです。
--
-- 既存33件のmigrationが表現してきた全ての変更は、このbaseline（0_init）に
-- 内包済みであり、以後のPrismaのmigrationコマンドは0_initのみを参照します。

-- Generated by: prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
-- Generated at: 2026-09-11

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "event";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "public"."PlanTier" AS ENUM ('FREE', 'PRO', 'ULTRA');

-- CreateEnum
CREATE TYPE "public"."SubscriptionProvider" AS ENUM ('STRIPE', 'GOOGLE_PLAY', 'APPLE');

-- CreateTable
CREATE TABLE "public"."User" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "emailVerified" TIMESTAMP(3),
    "image" TEXT,
    "password" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastActiveAt" TIMESTAMP(3),

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."RefreshToken" (
    "id" TEXT NOT NULL,
    "principalId" TEXT NOT NULL,
    "streamerId" TEXT,
    "tokenHash" TEXT NOT NULL,
    "familyId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "absoluteExpiresAt" TIMESTAMP(3) NOT NULL,
    "revokedAt" TIMESTAMP(3),
    "replacedById" TEXT,

    CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."RefreshTokenReplay" (
    "oldTokenHash" TEXT NOT NULL,
    "principalId" TEXT NOT NULL,
    "streamerId" TEXT,
    "accessTokenEnc" TEXT NOT NULL,
    "refreshTokenEnc" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RefreshTokenReplay_pkey" PRIMARY KEY ("oldTokenHash")
);

-- CreateTable
CREATE TABLE "public"."Ambassador" (
    "id" TEXT NOT NULL,
    "principalId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Ambassador_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AmbassadorInvite" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "usedAt" TIMESTAMP(3),
    "usedByPrincipalId" TEXT,

    CONSTRAINT "AmbassadorInvite_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Subscription" (
    "id" TEXT NOT NULL,
    "principalId" TEXT NOT NULL,
    "plan" "public"."PlanTier" NOT NULL DEFAULT 'FREE',
    "provider" "public"."SubscriptionProvider",
    "providerSubscriptionId" TEXT,
    "stripePriceId" TEXT,
    "googleProductId" TEXT,
    "googleObfuscatedAccountId" TEXT,
    "appleProductId" TEXT,
    "appleAppAccountToken" TEXT,
    "rawStatus" TEXT,
    "entitlementActive" BOOLEAN NOT NULL DEFAULT false,
    "lastVerifiedAt" TIMESTAMP(3),
    "currentPeriodEnd" TIMESTAMP(3),
    "cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "stripeCustomerId" TEXT,
    "stripeSubscriptionId" TEXT,
    "status" TEXT,

    CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."StripeCustomerLink" (
    "principalId" TEXT NOT NULL,
    "stripeCustomerId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StripeCustomerLink_pkey" PRIMARY KEY ("principalId")
);

-- CreateTable
CREATE TABLE "public"."PendingPurchaseIntent" (
    "id" TEXT NOT NULL,
    "principalId" TEXT NOT NULL,
    "provider" "public"."SubscriptionProvider" NOT NULL,
    "token" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "consumedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PendingPurchaseIntent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    "providerEmail" TEXT,
    "appleClientId" TEXT,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "public"."tiktok_users" (
    "tiktokUid" TEXT NOT NULL,
    "tiktokHandle" TEXT,
    "nickname" TEXT,
    "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tiktok_users_pkey" PRIMARY KEY ("tiktokUid")
);

-- CreateTable
CREATE TABLE "public"."TiktokRoom" (
    "id" TEXT NOT NULL,
    "tiktokHandle" TEXT NOT NULL,
    "deviceId" TEXT,
    "workerId" INTEGER,
    "proxyKey" TEXT,
    "watchSource" TEXT,
    "watchSourceAt" TIMESTAMP(3),
    "lastCollabSourceRoomId" TEXT,
    "lastCollabSourceAt" TIMESTAMP(3),
    "specialWatch" BOOLEAN NOT NULL DEFAULT false,
    "listenerStatus" TEXT,
    "listenerMessage" TEXT,
    "listenerUpdatedAt" TIMESTAMP(3),
    "listenerActivity" TEXT,
    "listenerHealth" TEXT,
    "listenerReason" TEXT,
    "listenerRevision" BIGINT,
    "monitorUntil" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastWatchInstructedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "unhealthySince" TIMESTAMP(3),
    "notFoundStreak" INTEGER NOT NULL DEFAULT 0,
    "notFoundFirstAt" TIMESTAMP(3),
    "lastExistenceCheckAt" TIMESTAMP(3),
    "lastLowValueCheckAt" TIMESTAMP(3),
    "consecutiveBlockedCount" INTEGER NOT NULL DEFAULT 0,
    "monitoringSuspended" BOOLEAN NOT NULL DEFAULT false,
    "hostTiktokUid" TEXT NOT NULL,
    "handleStaleAt" TIMESTAMP(3),

    CONSTRAINT "TiktokRoom_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."tiktok_room_admin_audit_logs" (
    "id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "tiktokHandle" TEXT NOT NULL,
    "operatorEmail" TEXT NOT NULL,
    "detail" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tiktok_room_admin_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."room_monitor_leases" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "referenceId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "releasedAt" TIMESTAMP(3),

    CONSTRAINT "room_monitor_leases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."room_connection_intervals" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "endedAt" TIMESTAMP(3),
    "disconnectReason" TEXT,
    "lastHeartbeatAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "room_connection_intervals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."EulerSignUsage" (
    "id" TEXT NOT NULL,
    "requestedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "roomId" TEXT NOT NULL,
    "tiktokHandle" TEXT NOT NULL,
    "outcome" TEXT NOT NULL,
    "errorMessage" TEXT,
    "trigger" TEXT NOT NULL,
    "reason" TEXT,
    "role" TEXT NOT NULL,
    "workerIndex" INTEGER,
    "listenerEpoch" BIGINT,
    "assignedWorkerId" INTEGER,
    "credentialMode" TEXT NOT NULL,
    "streamerPrincipalIds" TEXT[],
    "agencyIds" TEXT[],
    "eventIds" TEXT[],
    "roomMonitorUntil" TIMESTAMP(3),

    CONSTRAINT "EulerSignUsage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ListenerEpoch" (
    "id" SERIAL NOT NULL,
    "role" TEXT,
    "workerIndex" INTEGER,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ListenerEpoch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Agency" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "apiKeyHash" TEXT,
    "maxWatchTargets" INTEGER NOT NULL DEFAULT 10,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Agency_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AgencyWatch" (
    "id" TEXT NOT NULL,
    "agencyId" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "tiktokHandle" TEXT NOT NULL,
    "label" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AgencyWatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Streamer" (
    "id" TEXT NOT NULL,
    "principalId" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "tiktokHandle" TEXT NOT NULL,
    "verificationCode" TEXT NOT NULL,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "verifiedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tiktokHandleChangedAt" TIMESTAMP(3),
    "roomId" TEXT,
    "overlayToken" TEXT,

    CONSTRAINT "Streamer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."overlay_coin_list_settings" (
    "streamerId" TEXT NOT NULL,
    "fontKey" TEXT NOT NULL DEFAULT 'default',
    "textStyleKey" TEXT NOT NULL DEFAULT 'gold-night',
    "strokeWidth" INTEGER NOT NULL DEFAULT 4,
    "bgStyle" TEXT NOT NULL DEFAULT 'transparent',
    "sortOrder" TEXT NOT NULL DEFAULT 'desc',
    "maxEntries" INTEGER NOT NULL DEFAULT 20,
    "rowGap" INTEGER NOT NULL DEFAULT 8,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "overlay_coin_list_settings_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."overlay_top_gift_settings" (
    "streamerId" TEXT NOT NULL,
    "fontKey" TEXT NOT NULL DEFAULT 'default',
    "textStyleKey" TEXT NOT NULL DEFAULT 'gold-night',
    "strokeWidth" INTEGER NOT NULL DEFAULT 4,
    "title" TEXT NOT NULL DEFAULT '本日最高ギフト',
    "senderDisplayMode" TEXT NOT NULL DEFAULT 'latest',
    "glowEnabled" BOOLEAN NOT NULL DEFAULT true,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "overlay_top_gift_settings_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."overlay_tap_list_settings" (
    "streamerId" TEXT NOT NULL,
    "fontKey" TEXT NOT NULL DEFAULT 'default',
    "textStyleKey" TEXT NOT NULL DEFAULT 'gold-night',
    "strokeWidth" INTEGER NOT NULL DEFAULT 4,
    "bgStyle" TEXT NOT NULL DEFAULT 'transparent',
    "maxEntries" INTEGER NOT NULL DEFAULT 20,
    "rowGap" INTEGER NOT NULL DEFAULT 8,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "overlay_tap_list_settings_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."overlay_like_contribution_settings" (
    "streamerId" TEXT NOT NULL,
    "fontKey" TEXT NOT NULL DEFAULT 'default',
    "textStyleKey" TEXT NOT NULL DEFAULT 'gold-night',
    "strokeWidth" INTEGER NOT NULL DEFAULT 4,
    "title" TEXT NOT NULL DEFAULT 'Likeありがとう！',
    "interval" INTEGER NOT NULL DEFAULT 50,
    "soundVolume" INTEGER NOT NULL DEFAULT 100,
    "balloonDesignKey" TEXT NOT NULL DEFAULT 'dark-glass',
    "countFontSize" INTEGER NOT NULL DEFAULT 42,
    "nameFontSize" INTEGER NOT NULL DEFAULT 34,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "overlay_like_contribution_settings_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."overlay_timer_settings" (
    "streamerId" TEXT NOT NULL,
    "durationMinutes" INTEGER NOT NULL DEFAULT 10,
    "durationSeconds" INTEGER NOT NULL DEFAULT 0,
    "headingText" TEXT NOT NULL DEFAULT 'カウントダウン',
    "endSoundKey" TEXT,
    "endSoundVolume" INTEGER NOT NULL DEFAULT 100,
    "minFloorMinutes" INTEGER NOT NULL DEFAULT 0,
    "maxCeilingMinutes" INTEGER NOT NULL DEFAULT 0,
    "countdownSoundEnabled" BOOLEAN NOT NULL DEFAULT false,
    "countdownSoundThresholdSeconds" INTEGER NOT NULL DEFAULT 5,
    "countdownSoundKey" TEXT,
    "countdownSoundVolume" INTEGER NOT NULL DEFAULT 100,
    "fontKey" TEXT NOT NULL DEFAULT 'default',
    "textStyleKey" TEXT NOT NULL DEFAULT 'gold-night',
    "strokeWidth" INTEGER NOT NULL DEFAULT 4,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "overlay_timer_settings_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."overlay_timer_gift_rules" (
    "id" TEXT NOT NULL,
    "streamerId" TEXT NOT NULL,
    "giftName" TEXT NOT NULL,
    "minutesDelta" DOUBLE PRECISION NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "overlay_timer_gift_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."overlay_timer_state" (
    "streamerId" TEXT NOT NULL,
    "running" BOOLEAN NOT NULL DEFAULT false,
    "endsAt" TIMESTAMP(3),
    "remainingMs" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "overlay_timer_state_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."overlay_contribution_settings" (
    "streamerId" TEXT NOT NULL,
    "displayReference" TEXT NOT NULL DEFAULT 'today',
    "displayDate" TEXT,
    "threshold" INTEGER NOT NULL DEFAULT 1000,
    "goalCount" INTEGER NOT NULL DEFAULT 5,
    "visibleRows" INTEGER NOT NULL DEFAULT 5,
    "nameMaxWidth" INTEGER NOT NULL DEFAULT 140,
    "align" TEXT NOT NULL DEFAULT 'left',
    "headingBackground" TEXT NOT NULL DEFAULT 'clear',
    "displaySpeed" INTEGER NOT NULL DEFAULT 3,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "overlay_contribution_settings_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."battle_history_filter_settings" (
    "streamerId" TEXT NOT NULL,
    "hideLowDiamondEnabled" BOOLEAN NOT NULL DEFAULT false,
    "threshold" INTEGER NOT NULL DEFAULT 100,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "battle_history_filter_settings_pkey" PRIMARY KEY ("streamerId")
);

-- CreateTable
CREATE TABLE "public"."AppSetting" (
    "key" TEXT NOT NULL,
    "value" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "public"."gifts" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "giftId" INTEGER NOT NULL,
    "giftName" TEXT NOT NULL,
    "giftPictureUrl" TEXT,
    "repeatCount" INTEGER NOT NULL DEFAULT 1,
    "diamondCount" INTEGER NOT NULL DEFAULT 0,
    "totalDiamonds" INTEGER NOT NULL DEFAULT 0,
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "timeSource" TEXT NOT NULL DEFAULT 'tiktok',
    "dayKey" TEXT NOT NULL,
    "orderId" TEXT,
    "groupId" TEXT,
    "msgId" TEXT,
    "giftType" INTEGER,
    "multiplierType" INTEGER,
    "multiplierValue" INTEGER,

    CONSTRAINT "gifts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."listener_comments" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "comment" TEXT NOT NULL,
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "timeSource" TEXT NOT NULL DEFAULT 'tiktok',
    "dayKey" TEXT NOT NULL,
    "msgId" TEXT,

    CONSTRAINT "listener_comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."gift_daily_listener_stats" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "dayKey" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "rowCount" INTEGER NOT NULL DEFAULT 0,
    "giftCount" INTEGER NOT NULL DEFAULT 0,
    "totalDiamonds" INTEGER NOT NULL DEFAULT 0,
    "firstReceivedAt" TIMESTAMP(3) NOT NULL,
    "lastReceivedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "gift_daily_listener_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."gift_lifetime_stats" (
    "tiktokUid" TEXT NOT NULL,
    "rowCount" INTEGER NOT NULL DEFAULT 0,
    "giftCount" INTEGER NOT NULL DEFAULT 0,
    "totalDiamonds" BIGINT NOT NULL DEFAULT 0,
    "firstSeenAt" TIMESTAMP(3) NOT NULL,
    "lastSeenAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "gift_lifetime_stats_pkey" PRIMARY KEY ("tiktokUid")
);

-- CreateTable
CREATE TABLE "public"."tiktok_gift_catalog" (
    "giftId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "labelJa" TEXT,
    "diamondCount" INTEGER NOT NULL DEFAULT 0,
    "imageUrl" TEXT,
    "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tiktok_gift_catalog_pkey" PRIMARY KEY ("giftId")
);

-- CreateTable
CREATE TABLE "public"."tiktok_battles" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "action" INTEGER NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "startedAtEstimated" BOOLEAN NOT NULL DEFAULT true,
    "endedAt" TIMESTAMP(3),
    "durationSec" INTEGER,
    "hostTiktokUids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "hostDisplayIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "hostScores" JSONB NOT NULL DEFAULT '{}',
    "hostProfiles" JSONB NOT NULL DEFAULT '{}',
    "hostTeams" JSONB NOT NULL DEFAULT '{}',
    "opponentWatch" JSONB NOT NULL DEFAULT '{}',
    "tapPointsTracked" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tiktok_battles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."tiktok_battle_item_uses" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "cardType" INTEGER NOT NULL,
    "senderTiktokUid" TEXT NOT NULL,
    "senderProfilePictureUrl" TEXT,
    "targetHostTiktokUid" TEXT NOT NULL,
    "msgId" TEXT,
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tiktok_battle_item_uses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."tiktok_battle_bonus_missions" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "targetType" INTEGER NOT NULL,
    "progressTarget" INTEGER NOT NULL,
    "rewardMultiple" INTEGER NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "settledAt" TIMESTAMP(3),
    "taskResult" INTEGER,
    "rewardStartedAt" TIMESTAMP(3),
    "rewardEndedAt" TIMESTAMP(3),
    "rewardSum" INTEGER,

    CONSTRAINT "tiktok_battle_bonus_missions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."tiktok_battle_armies_snapshots" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tiktokUid" TEXT NOT NULL,
    "score" TEXT NOT NULL,

    CONSTRAINT "tiktok_battle_armies_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."tiktok_battle_tap_points" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "hostTiktokUid" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "points" INTEGER NOT NULL,

    CONSTRAINT "tiktok_battle_tap_points_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."battle_histories" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "windowStart" TIMESTAMP(3) NOT NULL,
    "windowEnd" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL,
    "selfScore" TEXT,
    "opponentScore" TEXT,
    "selfTotalDiamonds" INTEGER NOT NULL DEFAULT 0,
    "sourceUpdatedAt" TIMESTAMP(3) NOT NULL,
    "finalizedAt" TIMESTAMP(3) NOT NULL,
    "openingMultiplier" INTEGER,
    "openingMultiplierBasisGiftId" TEXT,
    "openingMultiplierConfidence" TEXT,
    "openingWindowStartedAt" TIMESTAMP(3),
    "openingWindowEndedAt" TIMESTAMP(3),
    "replayScorePointCount" INTEGER NOT NULL DEFAULT 0,
    "replayGiftEventCount" INTEGER NOT NULL DEFAULT 0,
    "shareToken" TEXT,
    "shareTokenIssuedAt" TIMESTAMP(3),

    CONSTRAINT "battle_histories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."contribution_share_tokens" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "period" TEXT NOT NULL,
    "date" TEXT,
    "startDatetime" TIMESTAMP(3),
    "endDatetime" TIMESTAMP(3),
    "rangeKey" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "contribution_share_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."battle_teams" (
    "id" TEXT NOT NULL,
    "battleHistoryId" TEXT NOT NULL,
    "externalTeamId" TEXT,
    "officialScore" TEXT,

    CONSTRAINT "battle_teams_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."battle_history_participants" (
    "id" TEXT NOT NULL,
    "battleHistoryId" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "teamIndex" INTEGER NOT NULL DEFAULT 0,
    "position" INTEGER NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "score" TEXT,
    "battleTeamId" TEXT,
    "roomId" TEXT,
    "isSelf" BOOLEAN,
    "tiktokHandleSnapshot" TEXT,
    "nicknameSnapshot" TEXT,
    "officialScore" TEXT,
    "observedGiftTotal" INTEGER,
    "captureStatus" TEXT,
    "captureCoverage" DOUBLE PRECISION,
    "captureStartedLateMs" INTEGER,
    "captureEndedEarlyMs" INTEGER,
    "captureGapMs" INTEGER,
    "monitoringStartedAt" TIMESTAMP(3),
    "firstConnectedAt" TIMESTAMP(3),
    "lastDisconnectedAt" TIMESTAMP(3),

    CONSTRAINT "battle_history_participants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."battle_history_gift_events" (
    "id" TEXT NOT NULL,
    "participantId" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "senderTiktokUid" TEXT NOT NULL,
    "senderTiktokHandleSnapshot" TEXT,
    "senderNicknameSnapshot" TEXT,
    "giftId" INTEGER NOT NULL,
    "giftNameSnapshot" TEXT NOT NULL,
    "repeatCount" INTEGER NOT NULL,
    "diamondCount" INTEGER NOT NULL,
    "totalDiamonds" INTEGER NOT NULL,
    "multiplierType" INTEGER,
    "multiplierValue" INTEGER,
    "senderGroupId" TEXT,
    "sourceGiftId" TEXT NOT NULL,

    CONSTRAINT "battle_history_gift_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."battle_history_item_card_events" (
    "id" TEXT NOT NULL,
    "participantId" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "cardType" INTEGER NOT NULL,
    "senderTiktokHandleSnapshot" TEXT,
    "senderNicknameSnapshot" TEXT,
    "senderTiktokUid" TEXT,

    CONSTRAINT "battle_history_item_card_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."battle_history_bonus_missions" (
    "id" TEXT NOT NULL,
    "battleHistoryId" TEXT NOT NULL,
    "participantId" TEXT NOT NULL,
    "targetType" INTEGER NOT NULL,
    "progressTarget" INTEGER NOT NULL,
    "rewardMultiple" INTEGER NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "settledAt" TIMESTAMP(3),
    "taskResult" INTEGER,
    "rewardStartedAt" TIMESTAMP(3),
    "rewardEndedAt" TIMESTAMP(3),
    "rewardSum" INTEGER,

    CONSTRAINT "battle_history_bonus_missions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."battle_history_score_points" (
    "id" TEXT NOT NULL,
    "battleHistoryId" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "offsetMs" INTEGER NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "score" TEXT NOT NULL,

    CONSTRAINT "battle_history_score_points_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."tiktok_avatar_assets" (
    "id" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "contentType" TEXT NOT NULL,
    "byteSize" INTEGER NOT NULL,
    "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tiktok_avatar_assets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."DbStatsSnapshot" (
    "id" TEXT NOT NULL,
    "runDate" DATE NOT NULL,
    "schemaName" TEXT NOT NULL,
    "tableName" TEXT NOT NULL,
    "rowCount" BIGINT NOT NULL,
    "totalBytes" BIGINT NOT NULL,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DbStatsSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."Event" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "coverImageKey" TEXT,
    "prizeText" TEXT,
    "noticeText" TEXT,
    "ownerPrincipalId" TEXT NOT NULL,
    "format" TEXT NOT NULL,
    "entryMode" TEXT NOT NULL,
    "teamPreset" TEXT NOT NULL DEFAULT 'GENERIC',
    "visibility" TEXT NOT NULL DEFAULT 'PRIVATE',
    "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
    "startAt" TIMESTAMP(3) NOT NULL,
    "endAt" TIMESTAMP(3) NOT NULL,
    "rules" JSONB NOT NULL DEFAULT '{}',
    "lastAggregatedAt" TIMESTAMP(3),
    "aggregateMs" INTEGER,
    "aggregationPolicy" TEXT,
    "finalizedAt" TIMESTAMP(3),
    "avatarsSnapshottedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventSession" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "name" TEXT,
    "startAt" TIMESTAMP(3) NOT NULL,
    "endAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EventSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventMultiplier" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "factor" DECIMAL(6,2) NOT NULL,
    "startAt" TIMESTAMP(3),
    "endAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EventMultiplier_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventTeam" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "colorHex" TEXT,
    "prefectureCode" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "EventTeam_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventParticipant" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "tiktokHandle" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "teamId" TEXT,
    "displayName" TEXT NOT NULL,
    "principalId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "avatarOffsetX" DOUBLE PRECISION,
    "avatarOffsetY" DOUBLE PRECISION,
    "avatarZoom" DOUBLE PRECISION,

    CONSTRAINT "EventParticipant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventRoomLease" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "tiktokUid" TEXT NOT NULL,
    "tiktokHandle" TEXT NOT NULL,
    "createdBySystem" BOOLEAN NOT NULL DEFAULT false,
    "monitorUntil" TIMESTAMP(3) NOT NULL,
    "releasedAt" TIMESTAMP(3),

    CONSTRAINT "EventRoomLease_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventMatch" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "round" INTEGER NOT NULL DEFAULT 1,
    "bracketPosition" INTEGER NOT NULL DEFAULT 0,
    "matchType" TEXT NOT NULL DEFAULT '1V1',
    "sessionId" TEXT NOT NULL,
    "scheduledStartAt" TIMESTAMP(3),
    "scheduledEndAt" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
    "detectedBattleId" TEXT,
    "detectedStartAt" TIMESTAMP(3),
    "detectedEndAt" TIMESTAMP(3),
    "detectionConfidence" TEXT,
    "detectedEndSource" TEXT,
    "winnerSideId" TEXT,
    "winnerDecidedBy" TEXT,
    "decidedAt" TIMESTAMP(3),
    "rules" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "EventMatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventMatchBattleCandidate" (
    "id" TEXT NOT NULL,
    "matchId" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "endedAt" TIMESTAMP(3),
    "endedAtSource" TEXT,
    "confidence" TEXT NOT NULL,
    "ambiguous" BOOLEAN NOT NULL DEFAULT false,
    "organizerSelected" BOOLEAN NOT NULL DEFAULT false,
    "selected" BOOLEAN NOT NULL DEFAULT false,
    "combinedGroupId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EventMatchBattleCandidate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventMatchSide" (
    "id" TEXT NOT NULL,
    "matchId" TEXT NOT NULL,
    "sideIndex" INTEGER NOT NULL,
    "teamId" TEXT,
    "score" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "diamonds" BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT "EventMatchSide_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventMatchSideParticipant" (
    "id" TEXT NOT NULL,
    "sideId" TEXT NOT NULL,
    "participantId" TEXT NOT NULL,

    CONSTRAINT "EventMatchSideParticipant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventLifePoint" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "current" INTEGER NOT NULL,
    "max" INTEGER NOT NULL,
    "eliminatedAt" TIMESTAMP(3),

    CONSTRAINT "EventLifePoint_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventLifeLedger" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "matchId" TEXT,
    "delta" INTEGER NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EventLifeLedger_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventContribution" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "scopeId" TEXT NOT NULL DEFAULT '',
    "listenerTiktokUid" TEXT NOT NULL,
    "listenerTiktokHandle" TEXT,
    "diamonds" BIGINT NOT NULL DEFAULT 0,
    "points" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "giftCount" INTEGER NOT NULL DEFAULT 0,
    "topParticipantId" TEXT,
    "participantCount" INTEGER NOT NULL DEFAULT 0,
    "breakdown" JSONB,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EventContribution_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."EventStanding" (
    "id" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "diamonds" BIGINT NOT NULL DEFAULT 0,
    "points" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "rank" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EventStanding_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "event"."DetectedBattle" (
    "id" TEXT NOT NULL,
    "battleId" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "startedAtEstimated" BOOLEAN NOT NULL DEFAULT true,
    "endedAt" TIMESTAMP(3),
    "durationSec" INTEGER,
    "lastAction" INTEGER NOT NULL,
    "hostTiktokUids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "hostDisplayIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "hostScores" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DetectedBattle_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "public"."User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "RefreshToken_tokenHash_key" ON "public"."RefreshToken"("tokenHash");

-- CreateIndex
CREATE INDEX "RefreshToken_principalId_idx" ON "public"."RefreshToken"("principalId");

-- CreateIndex
CREATE INDEX "RefreshToken_familyId_idx" ON "public"."RefreshToken"("familyId");

-- CreateIndex
CREATE UNIQUE INDEX "Ambassador_principalId_key" ON "public"."Ambassador"("principalId");

-- CreateIndex
CREATE UNIQUE INDEX "AmbassadorInvite_token_key" ON "public"."AmbassadorInvite"("token");

-- CreateIndex
CREATE INDEX "AmbassadorInvite_expiresAt_idx" ON "public"."AmbassadorInvite"("expiresAt");

-- CreateIndex
CREATE INDEX "Subscription_principalId_entitlementActive_idx" ON "public"."Subscription"("principalId", "entitlementActive");

-- CreateIndex
CREATE UNIQUE INDEX "Subscription_provider_providerSubscriptionId_key" ON "public"."Subscription"("provider", "providerSubscriptionId");

-- CreateIndex
CREATE UNIQUE INDEX "StripeCustomerLink_stripeCustomerId_key" ON "public"."StripeCustomerLink"("stripeCustomerId");

-- CreateIndex
CREATE UNIQUE INDEX "PendingPurchaseIntent_provider_token_key" ON "public"."PendingPurchaseIntent"("provider", "token");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "public"."Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "public"."Session"("sessionToken");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "public"."VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "public"."VerificationToken"("identifier", "token");

-- CreateIndex
CREATE INDEX "tiktok_users_tiktokHandle_idx" ON "public"."tiktok_users"("tiktokHandle");

-- CreateIndex
CREATE UNIQUE INDEX "TiktokRoom_hostTiktokUid_key" ON "public"."TiktokRoom"("hostTiktokUid");

-- CreateIndex
CREATE INDEX "TiktokRoom_workerId_monitorUntil_idx" ON "public"."TiktokRoom"("workerId", "monitorUntil");

-- CreateIndex
CREATE INDEX "TiktokRoom_listenerStatus_unhealthySince_idx" ON "public"."TiktokRoom"("listenerStatus", "unhealthySince");

-- CreateIndex
CREATE INDEX "TiktokRoom_tiktokHandle_idx" ON "public"."TiktokRoom"("tiktokHandle");

-- CreateIndex
CREATE INDEX "TiktokRoom_lastCollabSourceRoomId_idx" ON "public"."TiktokRoom"("lastCollabSourceRoomId");

-- CreateIndex
CREATE INDEX "tiktok_room_admin_audit_logs_roomId_idx" ON "public"."tiktok_room_admin_audit_logs"("roomId");

-- CreateIndex
CREATE INDEX "tiktok_room_admin_audit_logs_createdAt_idx" ON "public"."tiktok_room_admin_audit_logs"("createdAt");

-- CreateIndex
CREATE INDEX "room_monitor_leases_roomId_releasedAt_expiresAt_idx" ON "public"."room_monitor_leases"("roomId", "releasedAt", "expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "room_monitor_leases_roomId_reason_referenceId_key" ON "public"."room_monitor_leases"("roomId", "reason", "referenceId");

-- CreateIndex
CREATE INDEX "room_connection_intervals_roomId_startedAt_idx" ON "public"."room_connection_intervals"("roomId", "startedAt");

-- CreateIndex
CREATE INDEX "room_connection_intervals_roomId_endedAt_idx" ON "public"."room_connection_intervals"("roomId", "endedAt");

-- CreateIndex
CREATE INDEX "EulerSignUsage_roomId_createdAt_idx" ON "public"."EulerSignUsage"("roomId", "createdAt");

-- CreateIndex
CREATE INDEX "EulerSignUsage_tiktokHandle_createdAt_idx" ON "public"."EulerSignUsage"("tiktokHandle", "createdAt");

-- CreateIndex
CREATE INDEX "EulerSignUsage_createdAt_idx" ON "public"."EulerSignUsage"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "Agency_email_key" ON "public"."Agency"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Agency_apiKeyHash_key" ON "public"."Agency"("apiKeyHash");

-- CreateIndex
CREATE INDEX "AgencyWatch_roomId_idx" ON "public"."AgencyWatch"("roomId");

-- CreateIndex
CREATE UNIQUE INDEX "AgencyWatch_agencyId_roomId_key" ON "public"."AgencyWatch"("agencyId", "roomId");

-- CreateIndex
CREATE UNIQUE INDEX "Streamer_principalId_key" ON "public"."Streamer"("principalId");

-- CreateIndex
CREATE UNIQUE INDEX "Streamer_overlayToken_key" ON "public"."Streamer"("overlayToken");

-- CreateIndex
CREATE INDEX "Streamer_roomId_idx" ON "public"."Streamer"("roomId");

-- CreateIndex
CREATE UNIQUE INDEX "overlay_timer_gift_rules_streamerId_giftName_key" ON "public"."overlay_timer_gift_rules"("streamerId", "giftName");

-- CreateIndex
CREATE INDEX "gifts_roomId_dayKey_idx" ON "public"."gifts"("roomId", "dayKey");

-- CreateIndex
CREATE INDEX "gifts_roomId_receivedAt_idx" ON "public"."gifts"("roomId", "receivedAt");

-- CreateIndex
CREATE INDEX "gifts_roomId_tiktokUid_idx" ON "public"."gifts"("roomId", "tiktokUid");

-- CreateIndex
CREATE INDEX "gifts_roomId_groupId_idx" ON "public"."gifts"("roomId", "groupId");

-- CreateIndex
CREATE INDEX "gifts_roomId_msgId_idx" ON "public"."gifts"("roomId", "msgId");

-- CreateIndex
CREATE INDEX "gifts_dayKey_idx" ON "public"."gifts"("dayKey");

-- CreateIndex
CREATE UNIQUE INDEX "gifts_roomId_orderId_key" ON "public"."gifts"("roomId", "orderId");

-- CreateIndex
CREATE INDEX "listener_comments_roomId_dayKey_idx" ON "public"."listener_comments"("roomId", "dayKey");

-- CreateIndex
CREATE INDEX "listener_comments_roomId_receivedAt_idx" ON "public"."listener_comments"("roomId", "receivedAt");

-- CreateIndex
CREATE INDEX "listener_comments_dayKey_idx" ON "public"."listener_comments"("dayKey");

-- CreateIndex
CREATE INDEX "gift_daily_listener_stats_roomId_dayKey_idx" ON "public"."gift_daily_listener_stats"("roomId", "dayKey");

-- CreateIndex
CREATE INDEX "gift_daily_listener_stats_dayKey_idx" ON "public"."gift_daily_listener_stats"("dayKey");

-- CreateIndex
CREATE UNIQUE INDEX "gift_daily_listener_stats_roomId_dayKey_tiktokUid_key" ON "public"."gift_daily_listener_stats"("roomId", "dayKey", "tiktokUid");

-- CreateIndex
CREATE INDEX "tiktok_gift_catalog_name_idx" ON "public"."tiktok_gift_catalog"("name");

-- CreateIndex
CREATE INDEX "tiktok_battles_roomId_startedAt_idx" ON "public"."tiktok_battles"("roomId", "startedAt");

-- CreateIndex
CREATE INDEX "tiktok_battles_battleId_idx" ON "public"."tiktok_battles"("battleId");

-- CreateIndex
CREATE UNIQUE INDEX "tiktok_battles_roomId_battleId_key" ON "public"."tiktok_battles"("roomId", "battleId");

-- CreateIndex
CREATE INDEX "tiktok_battle_item_uses_roomId_battleId_idx" ON "public"."tiktok_battle_item_uses"("roomId", "battleId");

-- CreateIndex
CREATE INDEX "tiktok_battle_item_uses_roomId_msgId_idx" ON "public"."tiktok_battle_item_uses"("roomId", "msgId");

-- CreateIndex
CREATE INDEX "tiktok_battle_bonus_missions_roomId_battleId_idx" ON "public"."tiktok_battle_bonus_missions"("roomId", "battleId");

-- CreateIndex
CREATE INDEX "tiktok_battle_armies_snapshots_roomId_battleId_occurredAt_idx" ON "public"."tiktok_battle_armies_snapshots"("roomId", "battleId", "occurredAt");

-- CreateIndex
CREATE INDEX "tiktok_battle_tap_points_battleId_roomId_occurredAt_idx" ON "public"."tiktok_battle_tap_points"("battleId", "roomId", "occurredAt");

-- CreateIndex
CREATE UNIQUE INDEX "tiktok_battle_tap_points_roomId_battleId_tiktokUid_key" ON "public"."tiktok_battle_tap_points"("roomId", "battleId", "tiktokUid");

-- CreateIndex
CREATE UNIQUE INDEX "battle_histories_shareToken_key" ON "public"."battle_histories"("shareToken");

-- CreateIndex
CREATE INDEX "battle_histories_roomId_windowStart_idx" ON "public"."battle_histories"("roomId", "windowStart");

-- CreateIndex
CREATE UNIQUE INDEX "battle_histories_roomId_battleId_key" ON "public"."battle_histories"("roomId", "battleId");

-- CreateIndex
CREATE UNIQUE INDEX "contribution_share_tokens_token_key" ON "public"."contribution_share_tokens"("token");

-- CreateIndex
CREATE UNIQUE INDEX "contribution_share_tokens_roomId_rangeKey_key" ON "public"."contribution_share_tokens"("roomId", "rangeKey");

-- CreateIndex
CREATE INDEX "battle_teams_battleHistoryId_idx" ON "public"."battle_teams"("battleHistoryId");

-- CreateIndex
CREATE INDEX "battle_history_participants_battleTeamId_idx" ON "public"."battle_history_participants"("battleTeamId");

-- CreateIndex
CREATE UNIQUE INDEX "battle_history_participants_battleHistoryId_tiktokUid_key" ON "public"."battle_history_participants"("battleHistoryId", "tiktokUid");

-- CreateIndex
CREATE INDEX "battle_history_gift_events_participantId_occurredAt_idx" ON "public"."battle_history_gift_events"("participantId", "occurredAt");

-- CreateIndex
CREATE INDEX "battle_history_gift_events_participantId_senderTiktokUid_idx" ON "public"."battle_history_gift_events"("participantId", "senderTiktokUid");

-- CreateIndex
CREATE INDEX "battle_history_item_card_events_participantId_occurredAt_idx" ON "public"."battle_history_item_card_events"("participantId", "occurredAt");

-- CreateIndex
CREATE INDEX "battle_history_bonus_missions_battleHistoryId_idx" ON "public"."battle_history_bonus_missions"("battleHistoryId");

-- CreateIndex
CREATE INDEX "battle_history_bonus_missions_participantId_idx" ON "public"."battle_history_bonus_missions"("participantId");

-- CreateIndex
CREATE INDEX "battle_history_score_points_battleHistoryId_offsetMs_idx" ON "public"."battle_history_score_points"("battleHistoryId", "offsetMs");

-- CreateIndex
CREATE UNIQUE INDEX "tiktok_avatar_assets_tiktokUid_key" ON "public"."tiktok_avatar_assets"("tiktokUid");

-- CreateIndex
CREATE INDEX "DbStatsSnapshot_schemaName_tableName_runDate_idx" ON "public"."DbStatsSnapshot"("schemaName", "tableName", "runDate");

-- CreateIndex
CREATE UNIQUE INDEX "DbStatsSnapshot_runDate_schemaName_tableName_key" ON "public"."DbStatsSnapshot"("runDate", "schemaName", "tableName");

-- CreateIndex
CREATE UNIQUE INDEX "Event_slug_key" ON "event"."Event"("slug");

-- CreateIndex
CREATE INDEX "Event_status_endAt_idx" ON "event"."Event"("status", "endAt");

-- CreateIndex
CREATE INDEX "Event_ownerPrincipalId_idx" ON "event"."Event"("ownerPrincipalId");

-- CreateIndex
CREATE INDEX "EventSession_eventId_startAt_idx" ON "event"."EventSession"("eventId", "startAt");

-- CreateIndex
CREATE UNIQUE INDEX "EventSession_eventId_id_key" ON "event"."EventSession"("eventId", "id");

-- CreateIndex
CREATE INDEX "EventMultiplier_eventId_idx" ON "event"."EventMultiplier"("eventId");

-- CreateIndex
CREATE UNIQUE INDEX "EventTeam_eventId_name_key" ON "event"."EventTeam"("eventId", "name");

-- CreateIndex
CREATE UNIQUE INDEX "EventTeam_eventId_prefectureCode_key" ON "event"."EventTeam"("eventId", "prefectureCode");

-- CreateIndex
CREATE UNIQUE INDEX "EventParticipant_eventId_tiktokUid_key" ON "event"."EventParticipant"("eventId", "tiktokUid");

-- CreateIndex
CREATE UNIQUE INDEX "EventParticipant_eventId_roomId_key" ON "event"."EventParticipant"("eventId", "roomId");

-- CreateIndex
CREATE INDEX "EventRoomLease_roomId_releasedAt_idx" ON "event"."EventRoomLease"("roomId", "releasedAt");

-- CreateIndex
CREATE UNIQUE INDEX "EventRoomLease_eventId_roomId_key" ON "event"."EventRoomLease"("eventId", "roomId");

-- CreateIndex
CREATE INDEX "EventMatch_eventId_sessionId_idx" ON "event"."EventMatch"("eventId", "sessionId");

-- CreateIndex
CREATE INDEX "EventMatch_detectedBattleId_idx" ON "event"."EventMatch"("detectedBattleId");

-- CreateIndex
CREATE INDEX "EventMatchBattleCandidate_matchId_idx" ON "event"."EventMatchBattleCandidate"("matchId");

-- CreateIndex
CREATE UNIQUE INDEX "EventMatchBattleCandidate_matchId_battleId_key" ON "event"."EventMatchBattleCandidate"("matchId", "battleId");

-- CreateIndex
CREATE UNIQUE INDEX "EventMatchSide_matchId_sideIndex_key" ON "event"."EventMatchSide"("matchId", "sideIndex");

-- CreateIndex
CREATE UNIQUE INDEX "EventMatchSideParticipant_sideId_participantId_key" ON "event"."EventMatchSideParticipant"("sideId", "participantId");

-- CreateIndex
CREATE UNIQUE INDEX "EventLifePoint_eventId_subjectType_subjectId_key" ON "event"."EventLifePoint"("eventId", "subjectType", "subjectId");

-- CreateIndex
CREATE INDEX "EventLifeLedger_eventId_subjectType_subjectId_idx" ON "event"."EventLifeLedger"("eventId", "subjectType", "subjectId");

-- CreateIndex
CREATE INDEX "EventContribution_eventId_scope_scopeId_points_idx" ON "event"."EventContribution"("eventId", "scope", "scopeId", "points");

-- CreateIndex
CREATE INDEX "EventContribution_eventId_scope_scopeId_diamonds_idx" ON "event"."EventContribution"("eventId", "scope", "scopeId", "diamonds");

-- CreateIndex
CREATE UNIQUE INDEX "EventContribution_eventId_scope_scopeId_listenerTiktokUid_key" ON "event"."EventContribution"("eventId", "scope", "scopeId", "listenerTiktokUid");

-- CreateIndex
CREATE INDEX "EventStanding_eventId_subjectType_rank_idx" ON "event"."EventStanding"("eventId", "subjectType", "rank");

-- CreateIndex
CREATE UNIQUE INDEX "EventStanding_eventId_subjectType_subjectId_key" ON "event"."EventStanding"("eventId", "subjectType", "subjectId");

-- CreateIndex
CREATE INDEX "DetectedBattle_startedAt_idx" ON "event"."DetectedBattle"("startedAt");

-- CreateIndex
CREATE INDEX "DetectedBattle_roomId_startedAt_idx" ON "event"."DetectedBattle"("roomId", "startedAt");

-- CreateIndex
CREATE UNIQUE INDEX "DetectedBattle_battleId_roomId_key" ON "event"."DetectedBattle"("battleId", "roomId");

-- AddForeignKey
ALTER TABLE "public"."RefreshToken" ADD CONSTRAINT "RefreshToken_principalId_fkey" FOREIGN KEY ("principalId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Ambassador" ADD CONSTRAINT "Ambassador_principalId_fkey" FOREIGN KEY ("principalId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AmbassadorInvite" ADD CONSTRAINT "AmbassadorInvite_usedByPrincipalId_fkey" FOREIGN KEY ("usedByPrincipalId") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Subscription" ADD CONSTRAINT "Subscription_principalId_fkey" FOREIGN KEY ("principalId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."StripeCustomerLink" ADD CONSTRAINT "StripeCustomerLink_principalId_fkey" FOREIGN KEY ("principalId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PendingPurchaseIntent" ADD CONSTRAINT "PendingPurchaseIntent_principalId_fkey" FOREIGN KEY ("principalId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."room_monitor_leases" ADD CONSTRAINT "room_monitor_leases_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."room_connection_intervals" ADD CONSTRAINT "room_connection_intervals_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AgencyWatch" ADD CONSTRAINT "AgencyWatch_agencyId_fkey" FOREIGN KEY ("agencyId") REFERENCES "public"."Agency"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AgencyWatch" ADD CONSTRAINT "AgencyWatch_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Streamer" ADD CONSTRAINT "Streamer_principalId_fkey" FOREIGN KEY ("principalId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Streamer" ADD CONSTRAINT "Streamer_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_coin_list_settings" ADD CONSTRAINT "overlay_coin_list_settings_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_top_gift_settings" ADD CONSTRAINT "overlay_top_gift_settings_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_tap_list_settings" ADD CONSTRAINT "overlay_tap_list_settings_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_like_contribution_settings" ADD CONSTRAINT "overlay_like_contribution_settings_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_timer_settings" ADD CONSTRAINT "overlay_timer_settings_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_timer_gift_rules" ADD CONSTRAINT "overlay_timer_gift_rules_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."overlay_timer_settings"("streamerId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_timer_state" ADD CONSTRAINT "overlay_timer_state_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."overlay_contribution_settings" ADD CONSTRAINT "overlay_contribution_settings_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_filter_settings" ADD CONSTRAINT "battle_history_filter_settings_streamerId_fkey" FOREIGN KEY ("streamerId") REFERENCES "public"."Streamer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."gifts" ADD CONSTRAINT "gifts_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."listener_comments" ADD CONSTRAINT "listener_comments_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."tiktok_battles" ADD CONSTRAINT "tiktok_battles_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."tiktok_battle_item_uses" ADD CONSTRAINT "tiktok_battle_item_uses_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."tiktok_battle_bonus_missions" ADD CONSTRAINT "tiktok_battle_bonus_missions_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."tiktok_battle_armies_snapshots" ADD CONSTRAINT "tiktok_battle_armies_snapshots_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."tiktok_battle_tap_points" ADD CONSTRAINT "tiktok_battle_tap_points_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_histories" ADD CONSTRAINT "battle_histories_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."contribution_share_tokens" ADD CONSTRAINT "contribution_share_tokens_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "public"."TiktokRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_teams" ADD CONSTRAINT "battle_teams_battleHistoryId_fkey" FOREIGN KEY ("battleHistoryId") REFERENCES "public"."battle_histories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_participants" ADD CONSTRAINT "battle_history_participants_battleHistoryId_fkey" FOREIGN KEY ("battleHistoryId") REFERENCES "public"."battle_histories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_participants" ADD CONSTRAINT "battle_history_participants_battleTeamId_fkey" FOREIGN KEY ("battleTeamId") REFERENCES "public"."battle_teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_gift_events" ADD CONSTRAINT "battle_history_gift_events_participantId_fkey" FOREIGN KEY ("participantId") REFERENCES "public"."battle_history_participants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_item_card_events" ADD CONSTRAINT "battle_history_item_card_events_participantId_fkey" FOREIGN KEY ("participantId") REFERENCES "public"."battle_history_participants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_bonus_missions" ADD CONSTRAINT "battle_history_bonus_missions_battleHistoryId_fkey" FOREIGN KEY ("battleHistoryId") REFERENCES "public"."battle_histories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_bonus_missions" ADD CONSTRAINT "battle_history_bonus_missions_participantId_fkey" FOREIGN KEY ("participantId") REFERENCES "public"."battle_history_participants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."battle_history_score_points" ADD CONSTRAINT "battle_history_score_points_battleHistoryId_fkey" FOREIGN KEY ("battleHistoryId") REFERENCES "public"."battle_histories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventSession" ADD CONSTRAINT "EventSession_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMultiplier" ADD CONSTRAINT "EventMultiplier_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventTeam" ADD CONSTRAINT "EventTeam_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventParticipant" ADD CONSTRAINT "EventParticipant_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventParticipant" ADD CONSTRAINT "EventParticipant_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "event"."EventTeam"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventRoomLease" ADD CONSTRAINT "EventRoomLease_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMatch" ADD CONSTRAINT "EventMatch_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMatch" ADD CONSTRAINT "EventMatch_eventId_sessionId_fkey" FOREIGN KEY ("eventId", "sessionId") REFERENCES "event"."EventSession"("eventId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMatchBattleCandidate" ADD CONSTRAINT "EventMatchBattleCandidate_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "event"."EventMatch"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMatchSide" ADD CONSTRAINT "EventMatchSide_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "event"."EventMatch"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMatchSide" ADD CONSTRAINT "EventMatchSide_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "event"."EventTeam"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMatchSideParticipant" ADD CONSTRAINT "EventMatchSideParticipant_sideId_fkey" FOREIGN KEY ("sideId") REFERENCES "event"."EventMatchSide"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventMatchSideParticipant" ADD CONSTRAINT "EventMatchSideParticipant_participantId_fkey" FOREIGN KEY ("participantId") REFERENCES "event"."EventParticipant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventLifePoint" ADD CONSTRAINT "EventLifePoint_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventLifeLedger" ADD CONSTRAINT "EventLifeLedger_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventContribution" ADD CONSTRAINT "EventContribution_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "event"."EventStanding" ADD CONSTRAINT "EventStanding_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "event"."Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

