'use strict';

const fs = require('fs');

// TikTok LIVE ギフト名（英語）→日本語表示名の静的テーブル。
// キーは trim + 小文字化した英語ギフト名。未収録のギフトは元の名前をそのまま返す
// （表示が空になったり壊れたりしないようフォールバックする）。
// マッチング用の値（trigger.giftName 等）には使わないこと。あくまで表示専用。
//
// 対訳は必ず実際のTikTok（日本語環境）で確認できたものだけを追加すること。
// 推測での翻訳は追加しない（例: "TikTok Universe" は日本語環境でも英語表記のまま）。
// このブロックは /db/gift-ja-editor.html からの手動入力で自動書き換えされる。
// GIFT_NAME_JA_MAP:START
const GIFT_NAME_JA_MAP = {
    "a shard of hope": "希望のかけら",
    "adam’s dream": "アダムの夢",
    "alien buddy": "エイリアンの仲間",
    "amped up": "ボリュームアップ",
    "amusement park": "遊園地",
    "animal band": "アニマルバンド",
    "arabian cheetah": "アラビアのチーター",
    "astrobear": "アストロベアー",
    "aurora groove": "オーロラグルーヴ",
    "baby chicks": "ぴよぴよバード",
    "backing monkey": "シンバルの猿",
    "baglama": "バグラマ",
    "balloon crown": "ハートの風船",
    "banana peel": "バナナの皮",
    "baseball": "野球",
    "bat headwear": "コウモリの帽子",
    "batting cutie": "キュートなバッター",
    "battle champion": "バトルチャンピオン",
    "batwing hat": "コウモリ帽子",
    "beach maracas": "ビーチマラカス",
    "beat wings": "ビートウィング",
    "beating heart": "鼓動するハート",
    "become kitten": "子猫になる",
    "big shout out": "ビッグな叫び",
    "blast drum": "ブラストドラム",
    "bloom brass": "フラワーブラス",
    "bloom melody": "フラワーメロディ",
    "blooming heart": "花咲ハート",
    "blooming ribbons": "金の紙吹雪",
    "blossom fairy": "花の妖精",
    "blow a kiss": "投げキス",
    "blow rosie kisses": "ロージーの投げキス",
    "blue lightning": "青い稲妻",
    "bounce speakers": "跳ねるスピーカー",
    "bowknot": "蝶結び",
    "boxing gloves": "進撃グローブ",
    "bravo!": "ブラボー！",
    "bruiser": "ブルーザー",
    "bubble gum": "風船ガム",
    "bubbly kiss": "スイートな陽気",
    "budding heart": "ハートの誕生",
    "bunny dj": "バニーDJ",
    "butterfly for you": "あなたのための蝶",
    "butterfly vibe": "バタフライバイブ",
    "by the glaziers": "氷河とグレーズの海",
    "cactus shuffle": "カクタス・シャッフル",
    "cake slice": "ケーキ一切れ",
    "candy bouquet": "キャンディーのブーケ",
    "candy loot": "キャンディーをゲット",
    "candy puffs": "キャンディパフ",
    "cap": "キャップ",
    "captured vocals": "録音した音",
    "castle fantasy": "幻のキャッスル",
    "cat paws": "猫の足",
    "caterpillar chaos": "イモムシのカオス",
    "catrina": "カトリーナ",
    "celebration hat": "お祝いのハット",
    "celebration tape": "お祝いテープ",
    "celebration time": "お祝いの時間",
    "cello romance": "チェロロマンス",
    "charmer bow": "ハートハンターの矢",
    "chasing the dream": "夢を追いかける",
    "chatting popcorn": "おしゃべりポップコーン",
    "cheeky pup": "いたずらな子犬",
    "cheer for you": "あなたに送る歓声",
    "cheer mic": "応援マイク",
    "cheer you up": "元気出して",
    "cheering crab": "応援するカニ",
    "cheering towel": "応援タオル",
    "chick stampede": "ちびモブ大脱走",
    "chirpy kisses": "小鳥のキス",
    "chocolate": "チョコレート",
    "chopin in the rain": "雨の中のショパン",
    "chrono rewinder": "クロノリワインダー",
    "city pop": "シティポップ",
    "clap clap": "拍手",
    "cloud dj": "クラウドDJ",
    "clover hat": "クローバーハット",
    "clown boogie": "クラウン・ブギー",
    "club cheers": "応援クラブ",
    "club power": "団結クラブ",
    "club victory": "クラブ勝利",
    "coconut juice": "ココナッツジュース",
    "coffee magic": "コーヒーマジック",
    "coldy": "coldy",
    "colorful wings": "カラフルな翼",
    "come on!": "頑張れ！",
    "community heart": "コミュニティハート",
    "community rally": "コミュニティラリー",
    "community style": "コミュニティスタイル",
    "confetti": "クラッカー",
    "confetti bear": "クラッカーベア",
    "congratulations": "おめでとうございます",
    "cooper flies home": "クーパー、飛んで帰る",
    "coral": "サンゴ",
    "corgi": "コーギー",
    "corgi's drone show": "Corgi's Drone Show",
    "cow-napping": "牛の誘拐",
    "cozy xmas set": "あったかいクリスマスセット",
    "craft dreamer": "夢見るアーティスト",
    "creeper": "クリーパー",
    "crocodile": "ワニ",
    "crowd cheering": "観客の声援",
    "crystal dreams": "クリスタルドリーム",
    "crystal heart": "きらりハート",
    "cub on clouds": "雲の上のレオン",
    "cupid koala": "キューピッドのコアラ",
    "cute cat": "こんにちは旅行者",
    "cyber roar": "サイバーロア",
    "desert blitzy": "砂漠のブリッツ",
    "desert cooper": "砂漠のクーパー",
    "desert diny": "砂漠の恐竜",
    "desert tom": "砂漠のトム",
    "devoted heart": "ハートの絆",
    "diamond flight": "空飛ぶダイヤモンド",
    "diamond shield": "ダイヤの盾",
    "disco ball": "ミラーボール",
    "divine fingers": "神の指",
    "dj glasses": "DJメガネ",
    "dj set": "DJセット",
    "dj wave": "DJウェーブ",
    "djembe master": "ジェンベマスター",
    "doll new year greeting": "盾まろの新年あいさつ",
    "doughnut": "ドーナッツ",
    "dragon crown": "ドラゴンの冠",
    "dragon flame": "ドラゴンの炎",
    "dream big": "夢は大きく",
    "dream ride": "君と見る空",
    "dream team": "団結",
    "dreamy hat": "ドリーミーハット",
    "dreamy strings": "夢のような音色",
    "drum genius": "ドラムの天才",
    "drum hamster": "ドラム・ハムスター",
    "drum pop": "ドラムポップ",
    "duit raya": "ラヤグリーンパケット",
    "dynamic music": "ダイナミックミュージック",
    "echo mom": "エコーママ",
    "eid gift box": "イードのギフトボックス",
    "electro vibes": "エレクトロバイブス",
    "electronic love song": "エレクトロニックのラブソング",
    "encore clap": "アンコールの拍手",
    "energy capsule": "エネルギーカプセル",
    "epic pianist": "最高のピアニスト",
    "exclusive spark": "限定火花",
    "eye on the ball": "ボールに注意",
    "face-pulling": "いたずらおばけ",
    "fairy hide": "妖精のかくれんぼ",
    "fairy locket": "妖精ロケット",
    "fairy wings": "妖精の羽",
    "falcon": "ハヤブサ",
    "fan cat": "ファン猫",
    "fandom cheer": "FANDOM応援団",
    "fandom fan": "FANDOMうちわ",
    "fandom fever": "FANDOMフィーバー",
    "fandom stamp": "FANDOMスタンプ",
    "feather flock": "羽根",
    "feather mask": "羽根のマスク",
    "feather tiara": "羽のティアラ",
    "festival bracelet": "フェスのブレスレット",
    "fiery dragon": "ファイアリードラゴン",
    "fiesta accordion": "フィエスタアコーディオン",
    "finger heart": "フィンガーハート",
    "fire phoenix": "ファイアフェニックス",
    "firepit blitzy": "火山のブリッツ",
    "firepit cooper": "火山のクーパー",
    "firepit diny": "火山の恐竜",
    "firepit tom": "火山のトム",
    "fireworks": "花火",
    "flamingo floaty": "フラミンゴの浮き輪",
    "flamingo groove": "フラミンゴリズム",
    "floating octopus": "流れるタコ",
    "floral serenade": "フローラルセレナーデ",
    "flower headband": "花のカチューシャ",
    "fluffy buddies": "もふもふフレンズ",
    "fly love": "飛ぶ愛",
    "flying jets": "空飛ぶジェット機",
    "football": "サッカー",
    "forest elf": "森の小人",
    "forever rosa": "永遠のローザ",
    "fox legend": "尻尾が9本あるキツネ",
    "friendship necklace": "友情ネックレス",
    "frog conductor": "カエルの指揮者",
    "frozen magic": "雪の魔法",
    "fruit friends": "フルーツの友達",
    "fully bloomed sakura": "さくらの宝箱",
    "future city": "未来からの抱擁",
    "future encounter": "未来との遭遇",
    "future journey": "未来への旅",
    "g.o.a.t. busker": "G.O.A.T.バスカー",
    "galaxy": "銀河",
    "galaxy's bestest": "きゅんジェット",
    "garland headpiece": "花冠",
    "gate to treasure": "宝の門",
    "gem gun": "宝石銃",
    "genius": "天才",
    "gg": "GG",
    "gingerbread man": "ジンジャーブレッドマン",
    "glorious chef": "優れたシェフ",
    "glowing jellyfish": "光るクラゲ",
    "go hamster": "ハムスターに変身",
    "go home": "お家に帰る",
    "go popular": "人気アップ",
    "goal highlight-us": "ゴールハイライト：アメリカ",
    "golden gallop": "伝説の白馬",
    "good job": "よくできました",
    "gorilla": "ゴリラ",
    "grand show": "グランドショー",
    "greeting card": "メッセージカード",
    "greeting heart": "ハートタッチ",
    "groove clarinet": "グルーブクラリネット",
    "groove guitar": "グルーヴギター",
    "groove straw": "グルーヴハット",
    "guardian's pledge": "ガーディアンの誓い",
    "halloween fun hat": "ハロウィンファンハット",
    "hand heart": "ハートポーズ",
    "hands up": "いいね！",
    "happy party": "ハッピーパーティー",
    "hat and mustache": "帽子と口ひげ",
    "hat of joy": "楽しい帽子",
    "health potion": "健康のエキス",
    "heart": "ハート",
    "heart gaze": "ハートの視線",
    "heart guitar": "ハートのギター",
    "heart hood": "ハートのフード",
    "heart me": "ハートミー",
    "heart my earthling": "すきすきビーム",
    "hearts": "ハート",
    "here we go": "行くぞ",
    "hero landing": "スパイダーマン",
    "hi! rosie!": "ロージーのスタイル",
    "hip-hop hen": "ヒップホップのニワトリ",
    "hive escape": "巣からお出かけ",
    "honey strummer": "ミツバチとギターを鳴らす",
    "hug it better": "はぎゅっ",
    "hydrangea sea": "あじさいの海",
    "i like what i see": "メロメロ〜",
    "ice cream cone": "ソフトクリーム",
    "ice cream mic": "アイスクリームのマイク",
    "ice lolly": "アイスバー",
    "ignition check": "点火チェック",
    "infinite heart": "永遠のハート",
    "interstellar": "星から星へ",
    "intimacy": "深い関係",
    "invincible hammer": "無敵のハンマー",
    "it's match time": "Matchのお誘い！",
    "join butterflies": "輝く翼",
    "joker ball": "ジョーカーのボール",
    "jollie the joy bean": "楽しいビーンのジョリー",
    "jollie's community": "ジョリーのコミュニティ",
    "jollie's heartland": "ジョリーのハートランド",
    "journey pass": "ジャーニーパス",
    "joy floats": "空飛ぶお菓子",
    "juicy cap": "ジュースを飲むキャップ",
    "julius the champion": "絶対王者ジュリアス",
    "jungle blitzy": "ジャングルのブリッツ",
    "jungle cooper": "ジャングルのクーパー",
    "jungle diny": "ジャングルの恐竜",
    "jungle tom": "ジャングルのトム",
    "key master": "キーマスター",
    "kicker challenge": "サッカーチャレンジ",
    "king leonardo": "レオナルド王",
    "kitten kneading": "ふみふみする子猫",
    "kudos for my star": "推しへの称賛",
    "labor power": "労働パワー",
    "league ball": "リーグボール",
    "league countdown": "リーグカウントダウン",
    "league fandom": "リーグファンダム",
    "league trophy": "リーグトロフィー",
    "legend marcellus": "レジェンドのマーセラス",
    "leon and lili": "レオンとリリー",
    "leon and lion": "レオンとライオン",
    "leon the kitten": "子猫のレオン",
    "leon's sigil cape": "レオンの紋章マント",
    "leopard": "ヒョウ",
    "let butterfly dances": "蝶が踊る",
    "level ship": "レベルシップ",
    "level-up sparks": "ファンケーキ",
    "level-up spectacle": "レベルアップの壮観",
    "level-up spotlight": "レベルアップのスポットライト",
    "light castle": "ライトキャッスル",
    "like-pop": "ハートのバブルガン",
    "lili the leopard": "ヒョウのリリー",
    "lion": "ライオン",
    "little crown": "小さな王冠",
    "live ranking crown": "グランプリクラウン",
    "live ranking headband": "LIVE Ranking Headband",
    "live ranking ticket": "LIVE Ranking Ticket",
    "look up": "空を見上げて",
    "lost in your music": "あなたの音楽に夢中",
    "love call": "ラブコール",
    "love drop": "愛をお届け",
    "love flight": "ラブフライト",
    "love glasses": "恋のメガネ",
    "love in sunset": "夕日と愛",
    "love painting": "ラブペインティング",
    "love you": "愛してる",
    "love you so much": "大好き",
    "lover’s lock": "恋人のロック",
    "lucky airdrop box": "空中投下ラッキーボックス",
    "lucky crown": "幸運の王冠",
    "lucky pony": "しあわせポニー",
    "magic accordion": "マジックアコーディオン",
    "magic potion": "魔法の薬",
    "magic prop": "魔法のアイテム",
    "magic rhythm": "魔法のリズム",
    "magic world": "魔法の世界",
    "mark of love": "愛の印",
    "marked with love": "カラフルな軌跡",
    "maro spider man": "スパイダーマン発見",
    "marvelous confetti": "豪華なクラッカー",
    "masquerade": "ミステリーマスク",
    "match maniac": "Matchマニアック",
    "match master": "Matchマスター",
    "matchtacular!": "盛大なMatch！",
    "melodic birds": "鳥のさえずり",
    "melody glasses": "メロディグラス",
    "melody headset": "メロディヘッドセット",
    "meteor shower": "流星群",
    "mic champ": "マイクチャンピオン",
    "midsummer hair": "真夏のヘア",
    "mind blown": "衝撃的すぎ",
    "mishka bear": "ミシカベア",
    "mom's bonnet": "ママの帽子",
    "money gun": "マネーガン",
    "motorcycle": "オートバイ",
    "music  album": "音楽アルバム",
    "music bubbles": "シャボン玉のヘッドホン",
    "music burst": "ミュージックバースト",
    "music cloud": "音符雲",
    "music conductor": "音楽指揮者",
    "music mate": "音楽の友",
    "music on stage": "Music on Stage",
    "my dream stage": "夢のステージ",
    "my first rose": "最初のバラ",
    "mystery box": "ミステリーボックス",
    "mystery firework": "不思議な花火",
    "name shoutout": "名前の呼びかけ",
    "naughty chicken": "いたずら好きな鶏",
    "office penguin": "オフィスペンギン",
    "oldies": "オールディーズ",
    "out pops jollie!": "飛び出すジョリー！",
    "over the cloud": "雲の向こうへ",
    "overreact": "オーバーなリアクション",
    "palm breeze": "ヤシの木とそよ風",
    "panda snap": "パンダのスナップ",
    "papa capybara": "パパカピバラ",
    "paper crane": "折り鶴",
    "paris": "パリ",
    "party blossom": "パーティー満開",
    "party bus": "パーティーバス",
    "party laser": "パーティーレーザー",
    "party on&on": "パーティーは続く",
    "party pony": "パーティーポニー",
    "paw call": "肉球電話",
    "pearl chime": "パールチャイム",
    "pegasus": "ホワイトペガサス",
    "penguin snowpal": "ペンギンと雪だるま",
    "penlight": "ペンライト",
    "perfume": "香水",
    "phoenix": "フェニックス",
    "pinch face": "顔をつねる",
    "pink cowboy": "ピンクカウボーイ",
    "pirate's treasure": "海賊の宝",
    "play for you": "あなたに演奏",
    "poetry score": "詩の楽譜",
    "pony lantern": "ポニーのランタン",
    "pop": "ポップ",
    "pop parrot": "ポップなオウム",
    "popular vote": "人気アップ",
    "power chip": "パワーチップ",
    "powerful mind": "パワフルマインド",
    "prairie blitzy": "大草原のブリッツ",
    "prairie cooper": "大草原のクーパー",
    "prairie diny": "大草原の恐竜",
    "prairie tom": "大草原のトム",
    "premium shuttle": "プレミアムロケット",
    "private jet": "プライベートジェット",
    "punch cuddle": "パンチ君のハグ",
    "puppy kisses": "子犬のキス",
    "racing debut": "レースデビュー",
    "rain doll": "お天気占い",
    "rainbow slide": "虹のすべり台",
    "ramune": "ラムネ",
    "raving snail": "踊りまくるカタツムリ",
    "raya gift card": "ラヤのギフトカード",
    "red devil corgi": "Red Devil Corgi",
    "reindeer milk": "トナカイのミルク",
    "relaxed goose": "リラックスグース",
    "retro headset": "レトロヘッドセット",
    "retro melody": "レトロメロディ",
    "rhythm bot": "リズムボット",
    "rhythm crown": "リズムクラウン",
    "rhythmic bear": "リズミカルなクマ",
    "ring of honor-cube": "開運！栄光の輪",
    "rock and roll": "ロックンロール",
    "rock cats": "ロックキャッツ",
    "rock idol": "ロックアイドル",
    "rock star": "ロックスター",
    "rocking shroom": "ロックなマッシュルーム",
    "rocky the rock bean": "ロックビーンのロッキー",
    "rocky's punch": "ロッキーのパンチ",
    "roo mother": "ママカンガルー",
    "rosa": "ローザ",
    "rosa nebula": "ローザの星雲",
    "rose": "バラ",
    "rose bear": "ローズベア",
    "rose carriage": "バラ馬車",
    "rose soundwave": "ローズサウンドウェーブ",
    "rosie on stage": "ステージのロージー",
    "rosie the rose bean": "バラのビーンのロージー",
    "rosie's concert": "ロージーのサックス",
    "rust reforged": "眠れる戦士の復活",
    "rust vs world": "眠れる戦士 vs 世界",
    "sage the smart bean": "スマートビーンのセージ",
    "sage's coinbot": "セージのコインボット",
    "sage's slash": "セージの一攫千金",
    "sage’s venture": "セージの冒険",
    "sakura-style dj": "桜スタイルDJ",
    "sam in new city": "サムと未来都市",
    "samfaring tom": "サムとトムの航海",
    "santa owl surprise": "ふくろうサンタのサプライズ",
    "sax appeal": "らぶホーン",
    "sax groove": "サックスグルーヴ",
    "scroll": "巻物",
    "sea blitzy": "海のブリッツ",
    "sea cooper": "海のクーパー",
    "sea diny": "海の恐竜",
    "sea tom": "海のトム",
    "seahorse pop": "タツノオトシゴのポップ",
    "seaside romance": "海辺のロマンス",
    "semsemia": "セミア",
    "shateki-chocolate": "射的",
    "shell of a warrior": "ヘッドギア",
    "shine bright": "シャインブライト",
    "shiny air balloon": "ゆめ気球",
    "shoot the apple": "リンゴを撃つ",
    "signature jet": "サイン付きジェット機",
    "sing together": "一緒に歌おう",
    "singing frog": "歌うカエル",
    "singing magic": "歌って最高",
    "singing mushroom": "歌うキノコ",
    "singing sax": "歌うサックス",
    "single strike": "シングルストライク",
    "sky drift": "天空ドリフター",
    "skyforge citadel": "スカイフォージ要塞",
    "sloth peek": "ナマケモノのちら見",
    "slow motion": "スローモーション",
    "smile latte": "スマイルラテ",
    "sneaky jockey": "ちびゾンビ襲来！",
    "snow bloom": "雪の花",
    "so cute": "かわいい",
    "soccer holo": "LIVE Cupカード",
    "songs of live": "LIVEソング",
    "sound spell": "呪文のサウンド",
    "space love": "宇宙の愛",
    "sparkle dance": "キラキラダンス",
    "sparkle pony": "ポニーと花火",
    "spartan helmet": "オデュッセウスの兜",
    "spider web": "スパイダー盾まろ",
    "spider web 2.0": "スパイダー盾まろプレミアム",
    "spidey pin": "ヒーローの証",
    "sports car": "スポーツカー",
    "spring bouquet": "春のブーケ",
    "spring sprout": "春の芽吹き",
    "stabilizer": "スタビライザー",
    "stadium": "熱狂スタジアム",
    "stage of ring": "雨ふりステージ",
    "stage of spiderman": "親愛なる隣人",
    "star goggles": "スターメガネ",
    "star map polaris": "キラキラ星座",
    "star of red carpet": "レッドカーペットのスター",
    "starry fluff": "星付きふわふわ帽子",
    "steady on the beam": "ピッチの上でキープ",
    "storm blade": "ストームブレード",
    "stroke me": "なでられ待ち",
    "strong finish": "華麗なフィニッシュ",
    "style me up": "おしゃれに変身",
    "suitcase": "スーツケース",
    "summoning horn": "召喚の角笛",
    "sundae bowl": "ミニパフェ",
    "sunglasses": "サングラス",
    "sunny side up": "目玉焼き",
    "sunset speedway": "夕暮れを背に",
    "super dad": "スーパーパパ",
    "super popular": "スーパー人気",
    "superwoman": "スーパーウーマン",
    "suprised fish": "びっくりした魚",
    "surfing penguin": "波乗りペンギン",
    "surprise baby mob": "ちびモブ召喚",
    "swan": "白鳥",
    "sweet flutter": "スイートな蝶",
    "swing cello": "スイングチェロ",
    "take the mic": "マイクを握ろう",
    "team bracelet": "チームブレスレット",
    "tempo flute": "テンポフルート",
    "terminator face": "ターミネーターフェイス",
    "thumbs up": "グッド",
    "thunder falcon": "サンダーバード",
    "tidecaller trident": "潮呼びトライデント",
    "tiger lift": "タイガーの筋トレ",
    "tiktok": "TikTok",
    "tiktok shuttle": "TikTokシャトル",
    "tiktok stars": "TikTok Stars",
    "tiktok universe+": "TikTok Universe+",
    "tom thunderfoot": "スーパーカード",
    "tom's hug": "トムのハグ",
    "traffic cone": "カラーコーン",
    "train": "列車",
    "travel with you": "travel with me",
    "treasure clover": "宝のクローバー",
    "treasure's key": "宝の鍵",
    "treasured voice": "大切にされている声",
    "trending figure": "スポットライト",
    "triple thunder": "トリプルサンダー",
    "tundra blitzy": "ツンドラのブリッツ",
    "tundra cooper": "ツンドラのクーパー",
    "tundra diny": "ツンドラの恐竜",
    "tundra tom": "ツンドラのトム",
    "udon-nou": "うどん脳",
    "ukulele player": "ウクレレ演奏者",
    "ultimate fandom": "最強のFANDOM",
    "umbrella": "おさんぽ傘",
    "umbrella of love": "ラブシェルター",
    "under control": "すべてOK",
    "undersea kingdom": "深海王国",
    "unicorn": "ユニコーン",
    "unicorn fantasy": "伝説のユニコーン",
    "united heart": "つながる心",
    "valerian's oath": "ヴァレリアンの誓い",
    "valiant odyssey": "勇敢な冒険",
    "vibrant stage": "活気あふれるステージ",
    "viking hammer": "覇王のハンマー",
    "vintage flight": "ヴィンテージフライト",
    "vinyl flip": "レコードフリップ",
    "vocal bear": "マイクベア",
    "vr goggles": "タイムゴーグル",
    "wakey mallow": "お目覚めマロウ",
    "wave lights": "ウェーブライト",
    "whale diving": "クジラのダイビング",
    "white wolf": "ホワイトウルフ",
    "wild mic": "ワイルドマイク",
    "wink charm": "ウィンクする",
    "wink wink": "ウインク",
    "wishing cake": "お祝いケーキ",
    "wolf": "オオカミ",
    "work hard play harder": "たくさん働いてたくさん遊ぶ",
    "xmas tree hat": "クリスマスツリーの帽子",
    "xxxl flowers": "XXXL フラワー",
    "yellow lightning": "黄色い稲妻",
    "you’re amazing": "すばらしい！",
    "you're awesome": "素晴らしい",
    "you're so fly": "気分は上々！",
    "your concert": "あなたのコンサート",
    "zeus": "ゼウス"
};
// GIFT_NAME_JA_MAP:END

function normalizeGiftNameKey(name) {
    return String(name || '').trim().toLowerCase();
}

function getGiftDisplayNameJa(name) {
    const trimmed = String(name || '').trim();
    if (!trimmed) {
        return '';
    }

    return GIFT_NAME_JA_MAP[normalizeGiftNameKey(trimmed)] || trimmed;
}

function serializeGiftNameJaMapBlock() {
    const keys = Object.keys(GIFT_NAME_JA_MAP).sort((a, b) => a.localeCompare(b, 'en'));
    const entries = keys
        .map((key) => `    ${JSON.stringify(key)}: ${JSON.stringify(GIFT_NAME_JA_MAP[key])}`)
        .join(',\n');

    return `// GIFT_NAME_JA_MAP:START\nconst GIFT_NAME_JA_MAP = {\n${entries}\n};\n// GIFT_NAME_JA_MAP:END`;
}

function persistGiftNameJaMap() {
    const filePath = __filename;
    const source = fs.readFileSync(filePath, 'utf8');
    const blockPattern = /\/\/ GIFT_NAME_JA_MAP:START[\s\S]*?\/\/ GIFT_NAME_JA_MAP:END/;

    if (!blockPattern.test(source)) {
        throw new Error('GIFT_NAME_JA_MAP のマーカーが見つかりませんでした。');
    }

    fs.writeFileSync(filePath, source.replace(blockPattern, serializeGiftNameJaMapBlock()), 'utf8');
}

// /db/gift-ja-editor.html からの手動入力を反映する。value が空ならエントリを削除
// (英語名フォールバックに戻す)。呼び出し元がユーザーの目視確認を経た値のみ渡すこと。
function setGiftDisplayNameJa(rawName, value) {
    const key = normalizeGiftNameKey(rawName);
    if (!key) {
        return { ok: false, error: 'ギフト名が空です。' };
    }

    const trimmedValue = String(value || '').trim();

    if (trimmedValue) {
        GIFT_NAME_JA_MAP[key] = trimmedValue;
    } else {
        delete GIFT_NAME_JA_MAP[key];
    }

    persistGiftNameJaMap();

    return { ok: true, key, value: trimmedValue };
}

module.exports = {
    GIFT_NAME_JA_MAP,
    getGiftDisplayNameJa,
    setGiftDisplayNameJa
};
